/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scrabble;

import java.awt.GridLayout;
import javax.swing.*;

/**
 *
 * @author Mynor
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        llenarTablero();
        
        
        GridLayout experimentLayout = new GridLayout(Inicio.tableroLogico.x,Inicio.tableroLogico.y);
        this.jPanel1.setLayout(experimentLayout);
        
        
    }
    
    public final void llenarTablero(){
        for (int j = 0; j < Inicio.tableroLogico.y; j++){
            for (int i = 0; i < Inicio.tableroLogico.x; i++){
                Inicio.tableroLogico.buscarCasilla(i, j);
                Casilla casilla = new Casilla();
                casilla.x=Inicio.tableroLogico.x;
                casilla.y=Inicio.tableroLogico.y;
                //casilla.setText(""+Inicio.tableroLogico.actual.ficha.letra);
                this.jPanel1.add(casilla);
            }
        }
        //jPanel1.doLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelPalabras = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        PanelJugadores = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        PanelMatriz = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        PanelMano = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        PanelCola = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentResized(evt);
            }
        });

        PanelPalabras.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelPalabrasComponentShown(evt);
            }
        });
        PanelPalabras.setViewportView(jLabel2);

        jTabbedPane1.addTab("Diccionario de palabras", PanelPalabras);

        PanelJugadores.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelJugadoresComponentShown(evt);
            }
        });
        PanelJugadores.setViewportView(jLabel1);

        jTabbedPane1.addTab("Lista de jugadores", PanelJugadores);

        PanelMatriz.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelMatrizComponentShown(evt);
            }
        });

        jLabel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel3ComponentShown(evt);
            }
        });
        PanelMatriz.setViewportView(jLabel3);

        jTabbedPane1.addTab("Matriz del tablero", PanelMatriz);

        PanelMano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelManoMouseEntered(evt);
            }
        });
        PanelMano.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelManoComponentShown(evt);
            }
        });
        PanelMano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelManoFocusGained(evt);
            }
        });
        PanelMano.setViewportView(jLabel4);

        jTabbedPane1.addTab("Mano activa", PanelMano);

        PanelCola.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelColaComponentShown(evt);
            }
        });

        jLabel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel5ComponentShown(evt);
            }
        });
        PanelCola.setViewportView(jLabel5);

        jTabbedPane1.addTab("Cola de Fichas", PanelCola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentResized

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void PanelPalabrasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelPalabrasComponentShown
        // TODO add your handling code here:
        Icon imagenLS = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLSimple\\imagenLS.jpg");
        this.jLabel2.setIcon(imagenLS);
    }//GEN-LAST:event_PanelPalabrasComponentShown

    private void PanelJugadoresComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelJugadoresComponentShown
        // TODO add your handling code here:
        Icon imagenLC = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenLC.jpg");
        this.jLabel1.setIcon(imagenLC);
    }//GEN-LAST:event_PanelJugadoresComponentShown

    private void jLabel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3ComponentShown

    private void PanelManoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelManoComponentShown
        // TODO add your handling code here:
        Icon imagenLSM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg");
        this.jLabel4.setIcon(imagenLSM);
    }//GEN-LAST:event_PanelManoComponentShown

    private void jLabel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel5ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5ComponentShown

    private void PanelColaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelColaComponentShown
        // TODO add your handling code here:
        Icon imagenCL = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PCola\\imagenCL.jpg");
        this.jLabel5.setIcon(imagenCL);
    }//GEN-LAST:event_PanelColaComponentShown

    private void PanelMatrizComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelMatrizComponentShown
        // TODO add your handling code here:
        Icon imagenM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PMatriz\\imagenMatriz.jpg");
        this.jLabel3.setIcon(imagenM);
        this.jLabel3.repaint();
    }//GEN-LAST:event_PanelMatrizComponentShown

    private void PanelManoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelManoMouseEntered
        // TODO add your handling code here:
        Icon imagenLSM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg");
        this.jLabel4.setIcon(imagenLSM);
        this.jLabel4.repaint();
    }//GEN-LAST:event_PanelManoMouseEntered

    private void PanelManoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelManoFocusGained
        // TODO add your handling code here:
        //Icon imagenLSM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg");
        //this.jLabel4.setIcon(imagenLSM);
        //this.jLabel4.repaint();
    }//GEN-LAST:event_PanelManoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PanelCola;
    private javax.swing.JScrollPane PanelJugadores;
    private javax.swing.JScrollPane PanelMano;
    private javax.swing.JScrollPane PanelMatriz;
    private javax.swing.JScrollPane PanelPalabras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
