/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package scrabble;

import java.awt.Color;
import java.awt.GridLayout;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import static scrabble.Inicio.colaFichas;
import static scrabble.Inicio.lcJugadores;

/**
 *
 * @author Mynor
 */
public class Juego extends javax.swing.JFrame {
    
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        llenarTablero();
        
        
        GridLayout experimentLayout = new GridLayout(Inicio.tableroLogico.x,Inicio.tableroLogico.y);
        this.jPanel1.setLayout(experimentLayout);
        
        
    }
    
    public final void llenarTablero(){
        for (int j = 0; j < Inicio.tableroLogico.y; j++){
            for (int i = 0; i < Inicio.tableroLogico.x; i++){
                Inicio.tableroLogico.buscarCasilla(i, j);
                Casilla casilla = new Casilla();
                casilla.x=Inicio.tableroLogico.actual.x;
                casilla.y=Inicio.tableroLogico.actual.y;
                if(Inicio.tableroLogico.actual.multiple == 2){
                    casilla.setBackground(Color.blue);
                }
                if(Inicio.tableroLogico.actual.multiple == 3){
                    casilla.setBackground(Color.orange);
                }
                //casilla.setText(""+Inicio.tableroLogico.actual.ficha.letra);
                this.jPanel1.add(casilla);
            }
        }
        prepararFichas();
    }
    
    public void prepararFichas(){
        this.jLabel7.setText("Turno del jugador:"+Inicio.jugadorActual.nombre);
        Inicio.jugadorActual.mano.graficarMano(Inicio.jugadorActual.nombre);
        PCola.NodoCola letraActual = new PCola.NodoCola();
        letraActual=Inicio.jugadorActual.mano.inicio;
        char[] arregloMano = new char[7];
        for(int i=0;i<7;i++){
            arregloMano[i]=letraActual.letra;
            try{
                letraActual=letraActual.siguiente;
            }catch(Exception ex){
                letraActual=Inicio.jugadorActual.mano.inicio;
                System.out.print("se alcanzó el final de la mano");
            }
        }
        
        this.jButton1.setText(""+arregloMano[0]);
        this.jButton2.setText(""+arregloMano[1]);
        this.jButton3.setText(""+arregloMano[2]);
        this.jButton4.setText(""+arregloMano[3]);
        this.jButton5.setText(""+arregloMano[4]);
        this.jButton6.setText(""+arregloMano[5]);
        this.jButton7.setText(""+arregloMano[6]);
        
        this.jCheckBox1.setText(""+arregloMano[0]);
        this.jCheckBox2.setText(""+arregloMano[1]);
        this.jCheckBox3.setText(""+arregloMano[2]);
        this.jCheckBox4.setText(""+arregloMano[3]);
        this.jCheckBox5.setText(""+arregloMano[4]);
        this.jCheckBox6.setText(""+arregloMano[5]);
        this.jCheckBox7.setText(""+arregloMano[6]);
        
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelPalabras = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        PanelJugadores = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        PanelMano = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        PanelCola = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        PanelMatriz = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jButton11 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });

        PanelPalabras.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelPalabrasComponentShown(evt);
            }
        });
        PanelPalabras.setViewportView(jLabel2);

        jTabbedPane1.addTab("Diccionario de palabras", PanelPalabras);

        PanelJugadores.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelJugadoresComponentShown(evt);
            }
        });
        PanelJugadores.setViewportView(jLabel1);

        jTabbedPane1.addTab("Lista de jugadores", PanelJugadores);

        PanelMano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelManoMouseEntered(evt);
            }
        });
        PanelMano.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelManoComponentShown(evt);
            }
        });
        PanelMano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PanelManoFocusGained(evt);
            }
        });
        PanelMano.setViewportView(jLabel4);

        jTabbedPane1.addTab("Mano activa", PanelMano);

        PanelCola.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelColaComponentShown(evt);
            }
        });

        jLabel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel5ComponentShown(evt);
            }
        });
        PanelCola.setViewportView(jLabel5);

        jTabbedPane1.addTab("Cola de Fichas", PanelCola);

        PanelMatriz.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelMatrizComponentShown(evt);
            }
        });

        jLabel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel3ComponentShown(evt);
            }
        });
        PanelMatriz.setViewportView(jLabel3);

        jTabbedPane1.addTab("Matriz del tablero", PanelMatriz);

        jButton1.setText("_");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("_");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("_");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("_");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("_");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("_");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton8.setText("Validar Tiro");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("cancelar Tiro");

        jLabel6.setText("Nueva Palabra");

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Turno del Jugador:");

        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setText("jCheckBox2");

        jCheckBox3.setText("jCheckBox3");

        jCheckBox4.setText("jCheckBox4");

        jCheckBox5.setText("jCheckBox5");

        jCheckBox6.setText("jCheckBox6");

        jCheckBox7.setText("jCheckBox7");

        jButton11.setText("Cambiar fichas");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel8.setText("X:");

        jLabel9.setText("Y:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButton11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox5)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox7))))
                        .addGap(0, 174, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8)
                        .addComponent(jButton9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentResized

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void PanelPalabrasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelPalabrasComponentShown
        // TODO add your handling code here:
        //Icon imagenLS = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLSimple\\imagenLS.jpg");
        //this.jLabel2.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLSimple\\imagenLS.jpg"));
    }//GEN-LAST:event_PanelPalabrasComponentShown

    private void PanelJugadoresComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelJugadoresComponentShown
        // TODO add your handling code here:
        //Icon imagenLC = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenLC.jpg");
        //this.jLabel1.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenLC.jpg"));
    }//GEN-LAST:event_PanelJugadoresComponentShown

    private void jLabel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel3ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3ComponentShown

    private void PanelManoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelManoComponentShown
        // TODO add your handling code here:
        //Icon imagenLSM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg");
        //this.jLabel4.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg"));
    }//GEN-LAST:event_PanelManoComponentShown

    private void jLabel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel5ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5ComponentShown

    private void PanelColaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelColaComponentShown
        // TODO add your handling code here:
        //Icon imagenCL = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PCola\\imagenCL.jpg");
        //this.jLabel5.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PCola\\imagenCL.jpg"));
    }//GEN-LAST:event_PanelColaComponentShown

    private void PanelMatrizComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelMatrizComponentShown
        // TODO add your handling code here:
        //Icon imagenM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PMatriz\\imagenMatriz.jpg");
        //this.jLabel3.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PMatriz\\imagenMatriz.jpg"));
        //this.jLabel3.repaint();
    }//GEN-LAST:event_PanelMatrizComponentShown

    private void PanelManoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelManoMouseEntered
        // TODO add your handling code here:
       // Icon imagenLSM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg");
        //this.jLabel4.setIcon(imagenLSM);
    }//GEN-LAST:event_PanelManoMouseEntered

    private void PanelManoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PanelManoFocusGained
        // TODO add your handling code here:
        //Icon imagenLSM = new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg");
        //this.jLabel4.setIcon(imagenLSM);
        //this.jLabel4.repaint();
    }//GEN-LAST:event_PanelManoFocusGained

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
        //this.jLabel4.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg"));
        
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        
        
        int estado = jTabbedPane1.getSelectedIndex();
        switch(estado){
            case 0:
            {
                try
                {//
                    System.out.println("Refrescando la grafica del diccionario de palabras en la pestaña "+estado);
                    //this.jLabel2.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLSimple\\imagenLS.jpg"));
                    this.jLabel2.setIcon(new ImageIcon(ImageIO.read(new File ("src\\PLSimple\\imagenLS.jpg"))));
                }catch( Exception exp){
                    System.out.println("error al cargar la grafica de diccionario a la etiqueta: "+ exp);
                }
                break;
            }
            case 1:
            {
                try
                {//this.jLabel2.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLSimple\\imagenLS.jpg"));
                    System.out.println("Refrescando la grafica de Lista Circular de Jugadores en la pestaña "+estado);
                    //this.jLabel1.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenLC.jpg"));
                    this.jLabel1.setIcon(new ImageIcon(ImageIO.read(new File ("src\\PLCircular\\imagenLC.jpg"))));
                }catch( Exception exp){
                    System.out.println("error al cargar la imagen a la etiqueta: "+ exp);
                }
                break;
            }
            case 2:
                {
                try
                {
                    System.out.println("Refrescando la grafica de la matriz en la pestaña "+estado);
                    //this.jLabel3.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PMatriz\\imagenMatriz.jpg"));
                    this.jLabel3.setIcon(new ImageIcon(ImageIO.read(new File ("src\\PMatriz\\imagenMatriz.jpg"))));
                }catch( Exception exp){
                    System.out.println("error al cargar la imagen a la etiqueta: "+ exp);
                }
                break;
                }
            case 3:
                {
                try
                {
                    //new ImageIcon(ImageIO.read(new File ("src\\PLCircular\\imagenMano.jpg")))
                    System.out.println("Refrescando la grafica de la mano activa en la pestaña "+estado);
                    //this.jLabel4.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PLCircular\\imagenMano.jpg"));
                    this.jLabel4.setIcon(new ImageIcon(ImageIO.read(new File ("src\\PLCircular\\imagenMano.jpg"))));
                    //this.jLabel4.repaint();
                }catch( Exception exp){
                    System.out.println("error al cargar la imagen a la etiqueta: "+ exp);
                }
                break;
            }
            case 4:
                {
                try
                {
                    System.out.println("Refrescando la grafica de la cola de fichas en la pestaña "+estado);
                    //this.jLabel5.setIcon(new ImageIcon("C:\\Users\\Mynor\\Documents\\NetBeansProjects\\Scrabble\\src\\PCola\\imagenCL.jpg"));
                    //this.jLabel5.repaint();
                    this.jLabel5.setIcon(new ImageIcon(ImageIO.read(new File ("src\\PCola\\imagenCL.jpg"))));
                }catch( Exception exp){
                    System.out.println("error al cargar la imagen a la etiqueta: "+ exp);
                }
                break;
            }
            default:{
                    System.out.println("actualizando pestaña numero "+estado);
                
                break;
            }
        }
        //this.jTabbedPane1.repaint();
                //
            
        
        
        
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Inicio.tableroLogico.agregarLetra(Integer.parseInt(this.jTextField2.getText()),Integer.parseInt(this.jTextField3.getText()), this.jButton4.getText().charAt(0));
        this.prepararFichas();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Inicio.jugadorActual=Inicio.jugadorActual.siguiente;
        prepararFichas();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
    // TODO add your handling code here:
        if(this.jTextField1.getText()!=""){
        Inicio.lsPalabras.LSIncertFinal( this.jTextField1.getText());
        Inicio.lsPalabras.graficar();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        if(this.jCheckBox1.isSelected()){
            Inicio.jugadorActual.mano.CambiarFicha(this.jCheckBox1.getText().charAt(0));
        }
        if(this.jCheckBox2.isSelected()){
            Inicio.jugadorActual.mano.CambiarFicha(this.jCheckBox2.getText().charAt(0));
        }
        if(this.jCheckBox3.isSelected()){
            Inicio.jugadorActual.mano.CambiarFicha(this.jCheckBox3.getText().charAt(0));
        }
        if(this.jCheckBox4.isSelected()){
            Inicio.jugadorActual.mano.CambiarFicha(this.jCheckBox4.getText().charAt(0));
        }
        if(this.jCheckBox5.isSelected()){
            Inicio.jugadorActual.mano.CambiarFicha(this.jCheckBox5.getText().charAt(0));
        }
        if(this.jCheckBox6.isSelected()){
            Inicio.jugadorActual.mano.CambiarFicha(this.jCheckBox6.getText().charAt(0)); 
        }
        if(this.jCheckBox7.isSelected()){
            Inicio.jugadorActual.mano.CambiarFicha(this.jCheckBox7.getText().charAt(0));
        }
        colaFichas.graficar();
        Inicio.jugadorActual.mano.graficarMano(Inicio.jugadorActual.nombre); 
        this.prepararFichas();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Inicio.tableroLogico.agregarLetra(Integer.parseInt(this.jTextField2.getText()),Integer.parseInt(this.jTextField3.getText()), this.jButton1.getText().charAt(0));
        this.prepararFichas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Inicio.tableroLogico.agregarLetra(Integer.parseInt(this.jTextField2.getText()),Integer.parseInt(this.jTextField3.getText()), this.jButton2.getText().charAt(0));
        this.prepararFichas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Inicio.tableroLogico.agregarLetra(Integer.parseInt(this.jTextField2.getText()),Integer.parseInt(this.jTextField3.getText()), this.jButton3.getText().charAt(0));
        this.prepararFichas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Inicio.tableroLogico.agregarLetra(Integer.parseInt(this.jTextField2.getText()),Integer.parseInt(this.jTextField3.getText()), this.jButton5.getText().charAt(0));
        this.prepararFichas();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Inicio.tableroLogico.agregarLetra(Integer.parseInt(this.jTextField2.getText()),Integer.parseInt(this.jTextField3.getText()), this.jButton6.getText().charAt(0));
        this.prepararFichas();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Inicio.tableroLogico.agregarLetra(Integer.parseInt(this.jTextField2.getText()),Integer.parseInt(this.jTextField3.getText()), this.jButton7.getText().charAt(0));
        this.prepararFichas();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PanelCola;
    private javax.swing.JScrollPane PanelJugadores;
    private javax.swing.JScrollPane PanelMano;
    private javax.swing.JScrollPane PanelMatriz;
    private javax.swing.JScrollPane PanelPalabras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
